"""通用合同审查清单。"""
from __future__ import annotations

from services.contract_agent.schema import ChecklistItem


GENERIC_CHECKLIST = [
    ChecklistItem(
        id="GEN-SCOPE-001",
        contract_types=["unknown", "service", "sales", "saas", "software_development"],
        category="ambiguity",
        title="服务或交付范围不清",
        description="检查服务、商品、授权或交付成果是否具体。",
        risk_question="合同是否使用以甲方要求为准、另行确定等模糊表述？",
        severity_default="medium",
        risk_patterns=["以甲方要求为准", "另行确定", "具体以", "视情况"],
        suggested_fix="建议明确服务范围、交付成果、排除事项和变更流程。",
        proposed_text_template="双方确认，服务范围以本合同附件或双方书面确认的工作说明书为准；新增需求应经双方书面确认后执行。",
        impact=3,
        likelihood=4,
        detectability=3,
    ),
    ChecklistItem(
        id="GEN-PAYMENT-001",
        contract_types=["unknown", "service", "sales", "saas", "software_development", "lease", "loan"],
        category="payment",
        title="付款条件不清",
        description="检查金额、付款节点、发票、账户和逾期后果是否明确。",
        risk_question="合同是否明确约定付款金额、时间、条件和逾期责任？",
        severity_default="high",
        risk_patterns=["认为合适时支付", "另行支付", "适时支付", "付款时间另行确定", "支付服务费"],
        suggested_fix="建议明确付款金额、付款时间、付款触发条件、发票要求和逾期责任。",
        proposed_text_template="甲方应在乙方提交符合约定的发票及验收材料后五个工作日内支付对应服务费。",
        impact=4,
        likelihood=4,
        detectability=3,
    ),
    ChecklistItem(
        id="GEN-ACCEPT-001",
        contract_types=["unknown", "service", "sales", "saas", "software_development"],
        category="delivery_acceptance",
        title="验收标准不清或由一方单方确定",
        description="检查验收标准、期限、异议流程和整改机制是否客观。",
        risk_question="验收是否完全由一方单方决定，或缺少客观标准？",
        severity_default="high",
        risk_patterns=["验收标准由甲方单方确定", "甲方单方确定", "甲方认为合格", "验收标准另行确定"],
        suggested_fix="建议约定客观验收标准、验收期限、异议通知和整改次数。",
        proposed_text_template="验收应以本合同约定的功能、性能、交付清单和书面验收标准为依据；甲方应在收到交付成果后五个工作日内提出书面异议，逾期未提出的视为验收通过。",
        impact=4,
        likelihood=3,
        detectability=3,
    ),
    ChecklistItem(
        id="GEN-TERM-001",
        contract_types=["unknown", "service", "sales", "saas", "lease", "software_development"],
        category="termination",
        title="单方解除权过宽",
        description="检查解除条件是否明确、对等，是否有合理通知期。",
        risk_question="合同是否只赋予一方随时解除权或免除通知义务？",
        severity_default="high",
        risk_patterns=["随时解除", "无需通知", "单方解除", "可以随时解除"],
        suggested_fix="建议限定解除触发条件，并设置合理通知期和结算安排。",
        proposed_text_template="除本合同另有约定或一方严重违约外，任何一方提前解除合同应至少提前十五日书面通知对方，并就已完成部分进行结算。",
        impact=4,
        likelihood=3,
        detectability=3,
    ),
    ChecklistItem(
        id="GEN-BREACH-001",
        contract_types=["unknown", "service", "sales", "saas", "lease", "software_development", "nda"],
        category="breach",
        title="违约金过高或缺少区分",
        description="检查违约金是否区分违约程度，是否存在过高比例或每日累计风险。",
        risk_question="违约金是否不区分违约程度，或按每日、总价高比例累计？",
        severity_default="high",
        risk_patterns=["每日百分之", "违约金50%", "50%违约金", "全部租金作为违约金", "任何违约均应支付"],
        suggested_fix="建议区分一般违约和重大违约，并设置累计责任上限。",
        proposed_text_template="违约责任应与实际损失、违约程度和过错相匹配；除故意或重大过失外，累计赔偿责任不超过本合同总金额。",
        impact=5,
        likelihood=3,
        detectability=4,
    ),
    ChecklistItem(
        id="GEN-DISPUTE-MISS",
        contract_types=["unknown", "service", "sales", "saas", "lease", "software_development", "nda", "loan"],
        category="missing_clause",
        title="缺少争议解决条款",
        description="检查合同是否明确适用法律、管辖法院或仲裁机构。",
        risk_question="合同是否未见明确争议解决条款？",
        severity_default="medium",
        missing_clause_risk=True,
        positive_patterns=["争议", "管辖", "法院", "仲裁", "适用法律"],
        suggested_fix="建议补充适用法律、争议解决机构、地点和费用承担。",
        proposed_text_template="因本合同引起的或与本合同有关的争议，双方应先友好协商；协商不成的，任一方可向有管辖权的人民法院提起诉讼。",
        impact=3,
        likelihood=2,
        detectability=3,
    ),
]
